name: Build librespot.exe for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: x86_64-pc-windows-msvc

    - name: Build librespot
      run: cargo build --release

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: librespot.exe
        path: target/release/librespot.exe
